### PR TITLE
NEW: Writing_Bears: get_dependencies -> BEAR_DEPS

### PR DESCRIPTION
**Pull request by oreqizer**
https://github.com/coala-analyzer/documentation/issues/83

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, you caught up some commits that arent yours :p first of all you should do a ``git pull origin master`` where origin is the name of the official repo (or whatever its named for you) and then a ``git rebase -i origin`` and remove commits that arent meant to be in this PR :)

**Comment by oreqizer** [comment]
Ok after 15mins of rebasing and resetting, I hope I got this right 😅

**Comment by sils1297** [comment]
rename -> Rename

**Comment by sils1297** [comment]
sorry :P

**Comment by oreqizer** [comment]
solved

**Comment by Adrianzatreanu** [comment]
regarding commit message body:
1. it's -> its (grammar problem)
2. add a newline after the first period, if you have both sentences on same line it will be wrapped up ugly by github

also, use Closes instead of Fixes please :)

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/89/commits/b4f0dc8528240a4c0f57fa67e9c06bd246ce11e8

**Comment by Makman2** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
@Makman2 i am gonna cherry-pick this and merge it :)

**Comment by Asnelchristian** [comment]
besides it needs a rebase

**Comment by Asnelchristian** [comment]
check https://github.com/coala-analyzer/documentation/pull/92 :)

**Pull request closed without merging**
