### PR TITLE
Move docs from coala

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/7/commits/0da9b91a9a50ba942cc421fc48e9604b63bf7204

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/7/commits/ca83c9709e136d8bf922308eb56a1aa115e25724#diff-db4b047b30ffef7855b12b527860ac2c

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
oh in the yml you need to provide an empty script, we have that in some other repos somewhere I think...

**Comment by sils1297** [comment]
like echo nothing or so

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
