### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/77/commits/9b3dfc41b87362ee1d290adf539fa728416b54ef

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/77/commits/62c658caba38d64bc32c9b02e50e2618b21713b7

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/documentation/pull/77/commits/0a5b7d06a29fb4a31732527d55a01831aed71c74 https://github.com/coala-analyzer/documentation/pull/77/commits/8d7e509994b84b0e5508451c5d451bfacb194a72

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
