### PR TITLE
NEW: Add *.orig to .gitignore

### PR DESCRIPTION
**Pull request by oreqizer**
https://github.com/coala-analyzer/documentation/issues/84

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, the change is alright, but the commit message does not describe the action done. could you please take a fast look here and editing it :) ? http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

Thank you! By the way, to edit the last commit, use ``git commit --amend``, edit it, save it, and then push again with the extra flag ``--force`` :)

**Comment by oreqizer** [comment]
Hi, done!

**Comment by Adrianzatreanu** [comment]
looks good!

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
